use_frameworks!

platform :ios, '8.0'

target 'BinartCrypto_Example' do
  pod 'BinartCrypto', :path => '../'

  target 'BinartCrypto_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
